### ISSUE TITLE
Is this repo actively maintained?

### ISSUE THREAD

**Issue by ashpreetbedi** [scerelli/react-algoliasearch#13]
Planning on using this package (definitely makes things a lot simpler). Wanted to check if this is maintained?

**Comment by scerelli** [comment]
hi @ashpreetbedi it's not maintained because i'm not using this service anymore. If you want to use and and maintain it by yourself you could start off by doing some PRs which I'll make sure to review then once I'm confident that we're one the same page about how the library should be maintained I'd happily add you as a contributor.

**Comment by ashpreetbedi** [comment]
Thanks @scerelli, I actually just went ahead with using the algolia autocomplete widget. Thanks
