### ISSUE TITLE
Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by realph** [scerelli/react-algoliasearch#2]
I'm getting this error when I type inside my input field:

> index.js:77 Uncaught TypeError: Cannot read property 'value' of undefined

It's in reference to this line:

```
return _this2.props.currentLanguage ? _suggestion._highlightResult.name[_this2.props.currentLanguage].value : _suggestion._highlightResult.name.value;
```

Any idea what could be the issue. I'm rendering my component to page like so:

```
<AgAutocomplete
  apiKey={"redacted"}
  appId={"redacted"}
  index={"games"}
  inputId="input-search"
  placeholder="Search..."
/>
```

Any help is appreciated. Thanks in advance!

**Comment by scerelli** [comment]
Hi @realph are you sure that the `disaplayKey`inside your algolia data model has a value?

can you share an example of the data that algolia reutrns?

**Comment by odinti** [comment]
I've run into the same error and the problem was caused because because "name" was not present in the _higlitghtResult object

![no use](https://cloud.githubusercontent.com/assets/12376435/18420692/4686431a-783e-11e6-9104-f6b914a4ed49.png)

My only solution is change my model and every single reference to it through my whole app.

I suggest changing

`suggestion._highlightResult.name.value;`

to

`suggestion._highlightResult[displayKey].value;`

As I'm not familiar with the api a catch'em all solution could be

`for (first in suggestion._highlightResult) break;
suggestion._highlightResult[first].value;`

**Comment by scerelli** [comment]
thanks @odinti i'll update it as soon as possible. 

If you use algolia everyday you may know apis better then me so PR are welcome if you want :)
